package com.codeborne.json

import com.codeborne.json.assertions.JsonAssertions.assertThat
import org.junit.jupiter.api.Test

// Do not edit this file
class JsonParserComplianceTest {
  val parser = JsonParser()

  @Test fun nulls() {
    assertThat(parser.parse("null")).isEqualTo(null)
  }

  @Test fun booleans() {
    assertThat(parser.parse("true")).isEqualTo(true)
    assertThat(parser.parse("false")).isEqualTo(false)
  }
}
